create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text not null unique,
  password_hash text not null,
  display_name text not null,
  avatar text not null default '',
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists conversations (
  id bigint generated by default as identity primary key,
  name text not null default 'گفتگو',
  type text not null default 'group' check (type in ('direct','group','channel')),
  owner_id bigint references users(id) on delete set null,
  username text,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists conversations_channel_username_uq on conversations(username) where type='channel' and username is not null;

create table if not exists conversation_members (
  conversation_id bigint not null references conversations(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id,user_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references conversations(id) on delete cascade,
  sender_id bigint not null references users(id) on delete cascade,
  text text not null default '',
  file_url text not null default '',
  file_type text not null default '',
  file_name text not null default '',
  kind text not null default 'text',
  reply_to bigint references messages(id) on delete set null,
  created_at timestamptz not null default now(),
  deleted boolean not null default false,
  reactions jsonb not null default '{}'::jsonb
);
create index if not exists messages_conversation_id_id_idx on messages(conversation_id,id desc);

create table if not exists saved_messages (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  message_id bigint not null references messages(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id,message_id)
);
create table if not exists blocks (
  user_id bigint not null references users(id) on delete cascade,
  blocked_id bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,blocked_id),
  check(user_id<>blocked_id)
);
create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references users(id) on delete cascade,
  reported_id bigint not null references users(id) on delete cascade,
  reason text not null default '',
  created_at timestamptz not null default now()
);

-- Supabase Storage bucket. The backend uses the service-role key for uploads.
insert into storage.buckets (id, name, public)
values ('gish-files', 'gish-files', true)
on conflict (id) do update set public=true;

-- Public read policy for media URLs. Upload/delete remain server-only via service role.
drop policy if exists "gish public read" on storage.objects;
create policy "gish public read" on storage.objects for select using (bucket_id = 'gish-files');

-- v6.1 Telegram-inspired management/settings additions
alter table conversation_members add column if not exists role text not null default 'member';
alter table conversations add column if not exists photo text not null default '';
create table if not exists conversation_admins (
  conversation_id bigint not null references conversations(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  role text not null default 'admin' check (role in ('owner','admin','moderator')),
  permissions jsonb not null default '{"post":true,"edit":true,"delete":true,"invite":true,"ban":false,"manage":false}'::jsonb,
  created_at timestamptz not null default now(),
  primary key(conversation_id,user_id)
);
create table if not exists user_settings (
  user_id bigint primary key references users(id) on delete cascade,
  notifications jsonb not null default '{"messages":true,"sounds":true,"previews":true}'::jsonb,
  data_usage jsonb not null default '{"autoplay":true,"autoDownloadImages":true,"autoDownloadVideos":false,"autoDownloadAudio":false}'::jsonb,
  privacy jsonb not null default '{"lastSeen":"everyone","profilePhoto":"everyone","readReceipts":true}'::jsonb,
  security jsonb not null default '{"twoStep":false}'::jsonb,
  updated_at timestamptz not null default now()
);
