create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text not null unique,
  password_hash text not null,
  display_name text not null,
  avatar text not null default '',
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create table if not exists conversations (
  id bigint generated by default as identity primary key,
  name text not null default 'گفتگو',
  type text not null default 'group' check (type in ('direct','group','channel')),
  owner_id bigint references users(id) on delete set null,
  username text,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists conversations_channel_username_uq on conversations(username) where type='channel' and username is not null;

create table if not exists conversation_members (
  conversation_id bigint not null references conversations(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_message_id bigint not null default 0,
  primary key (conversation_id,user_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references conversations(id) on delete cascade,
  sender_id bigint not null references users(id) on delete cascade,
  text text not null default '',
  file_url text not null default '',
  file_type text not null default '',
  file_name text not null default '',
  kind text not null default 'text',
  reply_to bigint references messages(id) on delete set null,
  created_at timestamptz not null default now(),
  deleted boolean not null default false,
  reactions jsonb not null default '{}'::jsonb,
  media_meta jsonb not null default '{}'::jsonb
);
create index if not exists messages_conversation_id_id_idx on messages(conversation_id,id desc);

create table if not exists saved_messages (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  message_id bigint not null references messages(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id,message_id)
);
create table if not exists blocks (
  user_id bigint not null references users(id) on delete cascade,
  blocked_id bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,blocked_id),
  check(user_id<>blocked_id)
);
create table if not exists reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references users(id) on delete cascade,
  reported_id bigint not null references users(id) on delete cascade,
  reason text not null default '',
  created_at timestamptz not null default now()
);

-- Supabase Storage bucket. The backend uses the service-role key for uploads.
insert into storage.buckets (id, name, public)
values ('gish-files', 'gish-files', true)
on conflict (id) do update set public=true;

-- Public read policy for media URLs. Upload/delete remain server-only via service role.
drop policy if exists "gish public read" on storage.objects;
create policy "gish public read" on storage.objects for select using (bucket_id = 'gish-files');

-- v6.1 Telegram-inspired management/settings additions
alter table conversation_members add column if not exists role text not null default 'member';
alter table conversations add column if not exists photo text not null default '';
create table if not exists conversation_admins (
  conversation_id bigint not null references conversations(id) on delete cascade,
  user_id bigint not null references users(id) on delete cascade,
  role text not null default 'admin' check (role in ('owner','admin','moderator')),
  permissions jsonb not null default '{"post":true,"edit":true,"delete":true,"invite":true,"ban":false,"manage":false}'::jsonb,
  created_at timestamptz not null default now(),
  primary key(conversation_id,user_id)
);
create table if not exists user_settings (
  user_id bigint primary key references users(id) on delete cascade,
  notifications jsonb not null default '{"messages":true,"sounds":true,"previews":true}'::jsonb,
  data_usage jsonb not null default '{"autoplay":true,"autoDownloadImages":true,"autoDownloadVideos":false,"autoDownloadAudio":false}'::jsonb,
  privacy jsonb not null default '{"lastSeen":"everyone","profilePhoto":"everyone","readReceipts":true}'::jsonb,
  security jsonb not null default '{"twoStep":false}'::jsonb,
  updated_at timestamptz not null default now()
);

-- v6.7 advanced media editor metadata
alter table messages add column if not exists media_meta jsonb not null default '{}'::jsonb;


-- v6.8 presence, unread/read receipts and per-user message deletion
alter table users add column if not exists last_seen_at timestamptz not null default now();
alter table conversation_members add column if not exists last_read_message_id bigint not null default 0;
create index if not exists conversation_members_read_idx on conversation_members(conversation_id,last_read_message_id);
create table if not exists message_user_deletions (
  user_id bigint not null references users(id) on delete cascade,
  message_id bigint not null references messages(id) on delete cascade,
  deleted_at timestamptz not null default now(),
  primary key(user_id,message_id)
);


-- v6.8 stories
create table if not exists stories (id bigint generated by default as identity primary key,user_id bigint not null references users(id) on delete cascade,media_url text not null,media_type text not null default 'image',caption text not null default '',created_at timestamptz not null default now(),expires_at timestamptz not null default (now()+interval '24 hours'));
create index if not exists stories_expires_idx on stories(expires_at);

-- Gish Chat v6.9 feature extensions
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS settings jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS appearance jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS folders jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE user_settings ADD COLUMN IF NOT EXISTS chat_locks jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE IF NOT EXISTS profile_variants (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 name text NOT NULL, display_name text NOT NULL, avatar text NOT NULL DEFAULT '', bio text NOT NULL DEFAULT '',
 scope text NOT NULL DEFAULT 'friends', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS bots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 username text NOT NULL UNIQUE, name text NOT NULL, description text NOT NULL DEFAULT '', webhook_url text NOT NULL DEFAULT '', token text NOT NULL UNIQUE,
 created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE messages ADD COLUMN IF NOT EXISTS bot_id BIGINT REFERENCES bots(id) ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS bot_commands (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bot_id bigint NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
 command text NOT NULL, response text NOT NULL DEFAULT '', UNIQUE(bot_id,command)
);
CREATE TABLE IF NOT EXISTS botfather_sessions (
 user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
 step text NOT NULL DEFAULT 'idle',
 pending_name text NOT NULL DEFAULT '',
 pending_username text NOT NULL DEFAULT '',
 pending_bot_id bigint REFERENCES bots(id) ON DELETE SET NULL,
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS botfather_sessions_updated_idx ON botfather_sessions(updated_at);

-- Gish Chat v7.2 Stage 3: statistics, badges and advanced community management
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS settings jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE IF NOT EXISTS stage3_badges (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  icon text NOT NULL DEFAULT '🏆'
);
INSERT INTO stage3_badges(id,name,description,icon) VALUES
 ('active','کاربر فعال','حداقل ۱۰۰ پیام ارسال کرده‌ای','⭐'),
 ('old','عضو قدیمی','بیش از یک سال از عضویت گذشته است','🏅'),
 ('creator','سازنده گروه','حداقل یک گروه ساخته‌ای','👑'),
 ('creator-content','تولیدکننده محتوا','حداقل ۵۰ رسانه ارسال کرده‌ای','🎖️')
ON CONFLICT(id) DO NOTHING;
CREATE INDEX IF NOT EXISTS messages_sender_idx ON messages(sender_id,id DESC);
CREATE INDEX IF NOT EXISTS messages_file_idx ON messages(conversation_id,kind,id DESC);

-- Zento v7.4 Stage 4
ALTER TABLE bots ADD COLUMN IF NOT EXISTS bot_user_id BIGINT UNIQUE REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS avatar TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS about_text TEXT NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS privacy_mode BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS inline_mode BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS can_join_groups BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE bots ADD COLUMN IF NOT EXISTS can_read_all_group_messages BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE bot_commands ADD COLUMN IF NOT EXISTS reply_markup JSONB;
CREATE TABLE IF NOT EXISTS bot_chat_settings (
 bot_id BIGINT NOT NULL REFERENCES bots(id) ON DELETE CASCADE,
 conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
 can_post BOOLEAN NOT NULL DEFAULT true,
 can_read BOOLEAN NOT NULL DEFAULT true,
 can_manage BOOLEAN NOT NULL DEFAULT false,
 added_at TIMESTAMPTZ NOT NULL DEFAULT now(),
 PRIMARY KEY(bot_id,conversation_id)
);
CREATE INDEX IF NOT EXISTS bot_chat_settings_conv_idx ON bot_chat_settings(conversation_id);
CREATE INDEX IF NOT EXISTS bots_owner_idx ON bots(owner_id);
-- Real-time games are ephemeral and stored in server memory; no database table is required.
-- Multi-device sessions are represented by Socket.IO connections and do not persist device secrets.

-- v4.21 notifications / push subscriptions
create table if not exists push_subscriptions (
  id bigserial primary key,
  user_id bigint not null references users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists push_subscriptions_user_idx on push_subscriptions(user_id);
