const express=require('express');const http=require('http');const {Server}=require('socket.io');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');const multer=require('multer');const fs=require('fs');const path=require('path');
const app=express(),server=http.createServer(app),io=new Server(server);const PORT=process.env.PORT||3000,JWT_SECRET=process.env.JWT_SECRET||'change-this-gish-secret';
const dataDir=path.join(__dirname,'data'),dbFile=path.join(dataDir,'gish.json'),uploadDir=path.join(__dirname,'public','uploads');fs.mkdirSync(dataDir,{recursive:true});fs.mkdirSync(uploadDir,{recursive:true});
let db=loadDb();function loadDb(){try{const d=JSON.parse(fs.readFileSync(dbFile,'utf8'));return{users:d.users||[],conversations:d.conversations||[],messages:d.messages||[],saved:d.saved||[],blocks:d.blocks||[],reports:d.reports||[],nextUserId:d.nextUserId||1,nextConversationId:d.nextConversationId||1,nextMessageId:d.nextMessageId||1}}catch{return{users:[],conversations:[],messages:[],saved:[],blocks:[],reports:[],nextUserId:1,nextConversationId:1,nextMessageId:1}}}function saveDb(){const t=dbFile+'.tmp';fs.writeFileSync(t,JSON.stringify(db,null,2));fs.renameSync(t,dbFile)}
function safeUser(id){const u=db.users.find(x=>x.id===Number(id));return u?{id:u.id,username:u.username,email:u.email||'',display_name:u.display_name,avatar:u.avatar||'',bio:u.bio||''}:null}function isMember(cid,uid){const c=db.conversations.find(x=>x.id===Number(cid));return !!c&&c.members.includes(Number(uid))}function convView(c){const last=db.messages.filter(m=>m.conversation_id===c.id&&!m.deleted).sort((a,b)=>b.id-a.id)[0];return{id:c.id,name:c.name,type:c.type||'group',created_at:c.created_at,last_text:last?(last.kind==='voice'?'🎙️ پیام صوتی':last.kind==='image'?'🖼️ تصویر':last.kind==='video'?'🎬 ویدیو':last.kind==='audio'?'🎵 آهنگ':last.text||'📎 فایل'):'',last_time:last?last.created_at:c.created_at,members:c.members.map(safeUser).filter(Boolean),owner_id:c.owner_id||null,description:c.description||'',username:c.username||''}}
function seed(){if(!db.users.length){const h=bcrypt.hashSync('123456',10);for(const[u,n]of [['sara','سارا'],['ali','علی'],['maryam','مریم']])db.users.push({id:db.nextUserId++,username:u,email:u+'@gish.chat',password_hash:h,display_name:n,avatar:'',bio:'',created_at:new Date().toISOString()})}db.users.forEach(u=>{if(!u.email)u.email=u.username+'@gish.chat'});if(!db.conversations.some(c=>c.type==='group'))db.conversations.push({id:db.nextConversationId++,name:'گروه گیش چت',type:'group',members:db.users.map(u=>u.id),owner_id:db.users[0].id,description:'گروه دوستان گیش چت',created_at:new Date().toISOString()});if(!db.conversations.some(c=>c.type==='channel'))db.conversations.push({id:db.nextConversationId++,name:'اخبار گیش چت',type:'channel',members:db.users.map(u=>u.id),owner_id:db.users[0].id,username:'gishnews',description:'آخرین خبرها و اطلاعیه‌های گیش چت',created_at:new Date().toISOString()});saveDb()}seed();
app.use(express.json({limit:'3mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
const storage=multer.diskStorage({destination:uploadDir,filename:(_,f,cb)=>cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+path.extname(f.originalname))});const upload=multer({storage,limits:{fileSize:30*1024*1024}});
function tokenFor(u){return jwt.sign({id:u.id},JWT_SECRET,{expiresIn:'7d'})}function auth(req,res,next){try{const d=jwt.verify((req.headers.authorization||'').replace(/^Bearer\s+/i,''),JWT_SECRET),u=safeUser(d.id);if(!u)throw 0;req.user=u;next()}catch{res.status(401).json({error:'نشست نامعتبر است'})}}
app.post('/api/register',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),displayName=String(req.body.displayName||'').trim().slice(0,50);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<6||!displayName)return res.status(400).json({error:'ایمیل معتبر، نام نمایشی و رمز حداقل ۶ کاراکتری لازم است'});if(db.users.some(u=>String(u.email||'').toLowerCase()===email))return res.status(409).json({error:'این ایمیل قبلاً ثبت شده است'});let base=email.split('@')[0].replace(/[^a-z0-9_.-]/g,'').slice(0,24)||'user';let username=base,i=1;while(db.users.some(u=>u.username===username))username=base+(i++);const u={id:db.nextUserId++,username,email,password_hash:bcrypt.hashSync(password,10),display_name:displayName,avatar:'',bio:'',created_at:new Date().toISOString()};db.users.push(u);saveDb();res.json({token:tokenFor(u),user:safeUser(u.id)})});
app.post('/api/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase();const u=db.users.find(x=>String(x.email||'').toLowerCase()===email);if(!u||!bcrypt.compareSync(String(req.body.password||''),u.password_hash))return res.status(401).json({error:'ایمیل یا رمز عبور اشتباه است'});res.json({token:tokenFor(u),user:safeUser(u.id)})});app.get('/api/me',auth,(req,res)=>res.json(req.user));
app.get('/api/users',auth,(req,res)=>{const q=String(req.query.q||'').toLowerCase();res.json(db.users.filter(u=>u.id!==req.user.id&&(!q||u.username.includes(q)||u.display_name.toLowerCase().includes(q))).slice(0,50).map(u=>safeUser(u.id))) });
app.get('/api/conversations',auth,(req,res)=>res.json(db.conversations.filter(c=>c.members.includes(req.user.id)).sort((a,b)=>Math.max(0,...db.messages.filter(m=>m.conversation_id===b.id).map(m=>m.id))-Math.max(0,...db.messages.filter(m=>m.conversation_id===a.id).map(m=>m.id))).map(convView)));
app.post('/api/conversations/direct',auth,(req,res)=>{const other=Number(req.body.userId);if(!safeUser(other)||other===req.user.id)return res.status(400).json({error:'کاربر نامعتبر است'});let c=db.conversations.find(c=>c.type==='direct'&&c.members.length===2&&c.members.includes(req.user.id)&&c.members.includes(other));if(!c){c={id:db.nextConversationId++,name:'گفتگو',type:'direct',members:[req.user.id,other],created_at:new Date().toISOString()};db.conversations.push(c);saveDb()}res.json(convView(c))});
app.post('/api/conversations/group',auth,(req,res)=>{const name=String(req.body.name||'').trim().slice(0,60),members=[req.user.id,...(Array.isArray(req.body.members)?req.body.members.map(Number):[])].filter((v,i,a)=>v&&a.indexOf(v)===i&&safeUser(v));if(!name||members.length<2)return res.status(400).json({error:'نام گروه و حداقل یک عضو دیگر لازم است'});const c={id:db.nextConversationId++,name,type:'group',members,owner_id:req.user.id,description:String(req.body.description||'').trim().slice(0,200),created_at:new Date().toISOString()};db.conversations.push(c);saveDb();res.json(convView(c))});
app.post('/api/conversations/channel',auth,(req,res)=>{const name=String(req.body.name||'').trim().slice(0,60),username=String(req.body.username||'').trim().toLowerCase().replace(/[^a-z0-9_]/g,'').slice(0,30),description=String(req.body.description||'').trim().slice(0,200);if(!name||username.length<3)return res.status(400).json({error:'نام کانال و شناسه انگلیسی حداقل ۳ حرفی لازم است'});if(db.conversations.some(c=>c.type==='channel'&&c.username===username))return res.status(409).json({error:'این شناسه کانال قبلاً استفاده شده است'});const c={id:db.nextConversationId++,name,type:'channel',members:[req.user.id],owner_id:req.user.id,username,description,created_at:new Date().toISOString()};db.conversations.push(c);saveDb();res.json(convView(c))});
app.post('/api/conversations/:id/join',auth,(req,res)=>{const c=db.conversations.find(x=>x.id===Number(req.params.id));if(!c||c.type!=='channel')return res.status(404).json({error:'کانال پیدا نشد'});if(!c.members.includes(req.user.id))c.members.push(req.user.id);saveDb();res.json(convView(c))});
app.get('/api/conversations/:id/messages',auth,(req,res)=>{const cid=Number(req.params.id);if(!isMember(cid,req.user.id))return res.status(403).json({error:'ابتدا باید عضو این گفتگو باشید'});res.json(db.messages.filter(m=>m.conversation_id===cid).sort((a,b)=>a.id-b.id).slice(-300).map(m=>({...m,...(safeUser(m.sender_id)||{}),display_name:safeUser(m.sender_id)?.display_name,reactions:m.reactions||{}}))) });
app.post('/api/messages',auth,(req,res)=>{const cid=Number(req.body.conversationId),c=db.conversations.find(x=>x.id===cid);if(!c||!isMember(cid,req.user.id))return res.status(403).json({error:'گفتگو پیدا نشد یا عضو آن نیستید'});if(c.type==='channel'&&Number(c.owner_id)!==Number(req.user.id))return res.status(403).json({error:'فقط مدیر کانال می‌تواند پیام بفرستد'});if(c.type==='direct'){const otherId=c.members.find(x=>Number(x)!==Number(req.user.id));if((db.blocks||[]).some(x=>(Number(x.user_id)===Number(req.user.id)&&Number(x.blocked_id)===Number(otherId))||(Number(x.user_id)===Number(otherId)&&Number(x.blocked_id)===Number(req.user.id))))return res.status(403).json({error:'ارسال پیام به این کاربر مجاز نیست'});}const text=String(req.body.text||'').trim().slice(0,5000),replyTo=req.body.replyTo?Number(req.body.replyTo):null;if(!text)return res.status(400).json({error:'پیام خالی است'});const m={id:db.nextMessageId++,conversation_id:cid,sender_id:req.user.id,text,file_url:'',file_type:'',file_name:'',kind:'text',reply_to:replyTo,created_at:new Date().toISOString(),deleted:false,reactions:{}};db.messages.push(m);saveDb();const u=safeUser(req.user.id);const out={...m,display_name:u.display_name,username:u.username,avatar:u.avatar};io.to('conv:'+cid).emit('message',out);res.json(out)});
app.post('/api/upload',auth,upload.single('file'),(req,res)=>{if(!req.file)return res.status(400).json({error:'فایل ارسال نشده'});res.json({url:'/uploads/'+req.file.filename,name:req.file.originalname,size:req.file.size,mime:req.file.mimetype})});
app.put('/api/profile',auth,(req,res)=>{const name=String(req.body.displayName||'').trim().slice(0,50),bio=String(req.body.bio||'').trim().slice(0,160);if(!name)return res.status(400).json({error:'نام نامعتبر است'});const u=db.users.find(x=>x.id===req.user.id);u.display_name=name;u.bio=bio;saveDb();res.json(safeUser(u.id))});
app.post('/api/profile/avatar',auth,upload.single('avatar'),(req,res)=>{if(!req.file||!req.file.mimetype.startsWith('image/'))return res.status(400).json({error:'لطفاً یک تصویر انتخاب کنید'});const u=db.users.find(x=>x.id===req.user.id);u.avatar='/uploads/'+req.file.filename;saveDb();res.json(safeUser(u.id))});
app.get('/api/users/:id/profile',auth,(req,res)=>{const id=Number(req.params.id);if(!id)return res.status(400).json({error:'کاربر نامعتبر است'});const u=safeUser(id);if(!u)return res.status(404).json({error:'کاربر پیدا نشد'});const blocked=(db.blocks||[]).some(x=>x.user_id===req.user.id&&x.blocked_id===id);const blockedBy=(db.blocks||[]).some(x=>x.user_id===id&&x.blocked_id===req.user.id);res.json({...u,blocked,blockedBy})});
app.post('/api/users/:id/block',auth,(req,res)=>{const id=Number(req.params.id);if(!safeUser(id)||id===req.user.id)return res.status(400).json({error:'کاربر نامعتبر است'});db.blocks=db.blocks||[];const i=db.blocks.findIndex(x=>x.user_id===req.user.id&&x.blocked_id===id);if(i>=0)db.blocks.splice(i,1);else db.blocks.push({user_id:req.user.id,blocked_id:id,created_at:new Date().toISOString()});saveDb();res.json({blocked:i<0})});
app.post('/api/users/:id/report',auth,(req,res)=>{const id=Number(req.params.id),reason=String(req.body.reason||'رفتار نامناسب').trim().slice(0,200);if(!safeUser(id)||id===req.user.id)return res.status(400).json({error:'کاربر نامعتبر است'});db.reports=db.reports||[];db.reports.push({id:Date.now()+Math.random(),reporter_id:req.user.id,reported_id:id,reason,created_at:new Date().toISOString()});saveDb();res.json({ok:true})});
app.get('/api/saved',auth,(req,res)=>{const items=(db.saved||[]).filter(x=>x.user_id===req.user.id).sort((a,b)=>b.id-a.id).slice(0,500);res.json(items.map(x=>{const m=db.messages.find(mm=>mm.id===x.message_id);const u=m?safeUser(m.sender_id):null;return {...x,message:m?{...m,display_name:u?.display_name,username:u?.username,avatar:u?.avatar}:null}}).filter(x=>x.message));});
app.post('/api/saved/:messageId',auth,(req,res)=>{const mid=Number(req.params.messageId),m=db.messages.find(x=>x.id===mid);if(!m||!isMember(m.conversation_id,req.user.id))return res.status(404).json({error:'پیام پیدا نشد'});db.saved=db.saved||[];const exists=db.saved.find(x=>x.user_id===req.user.id&&x.message_id===mid);if(exists){db.saved=db.saved.filter(x=>x!==exists);saveDb();return res.json({saved:false})}db.saved.push({id:Date.now()+Math.random(),user_id:req.user.id,message_id:mid,created_at:new Date().toISOString()});saveDb();res.json({saved:true})});
const online=new Map();io.use((s,n)=>{try{s.user=jwt.verify(s.handshake.auth?.token||'',JWT_SECRET);n()}catch{n(new Error('unauthorized'))}});
io.on('connection',socket=>{const uid=Number(socket.user.id);online.set(uid,(online.get(uid)||0)+1);io.emit('presence',{userId:uid,online:true});socket.on('join',cid=>{if(isMember(Number(cid),uid))socket.join('conv:'+Number(cid))});socket.on('typing',d=>{if(isMember(Number(d.conversationId),uid))socket.to('conv:'+Number(d.conversationId)).emit('typing',{userId:uid,typing:!!d.typing})});socket.on('send_message',d=>{const cid=Number(d.conversationId),c=db.conversations.find(x=>x.id===cid);if(!c||!isMember(cid,uid))return;if(c.type==='direct'){const otherId=c.members.find(x=>x!==uid);if((db.blocks||[]).some(x=>(x.user_id===uid&&x.blocked_id===otherId)||(x.user_id===otherId&&x.blocked_id===uid)))return;}const text=String(d.text||'').trim().slice(0,5000),fileUrl=String(d.fileUrl||'').slice(0,500),fileType=String(d.fileType||'').slice(0,100),fileName=String(d.fileName||'').slice(0,200);if(!text&&!fileUrl)return;if(c.type==='channel'&&c.owner_id!==uid)return;const replyTo=d.replyTo?Number(d.replyTo):null;const m={id:db.nextMessageId++,conversation_id:cid,sender_id:uid,text,file_url:fileUrl,file_type:fileType,file_name:fileName,kind:String(d.kind||'text'),reply_to:replyTo,created_at:new Date().toISOString(),deleted:false,reactions:{}};db.messages.push(m);saveDb();const u=safeUser(uid);io.to('conv:'+cid).emit('message',{...m,display_name:u.display_name,username:u.username,avatar:u.avatar})});
socket.on('react',d=>{const m=db.messages.find(x=>x.id===Number(d.messageId));if(!m||!isMember(m.conversation_id,uid))return;const emoji=String(d.emoji||'').slice(0,8);if(!emoji)return;m.reactions=m.reactions||{};m.reactions[emoji]=m.reactions[emoji]||[];const arr=m.reactions[emoji];const i=arr.indexOf(uid);if(i>=0)arr.splice(i,1);else arr.push(uid);if(!arr.length)delete m.reactions[emoji];saveDb();io.to('conv:'+m.conversation_id).emit('reaction',{messageId:m.id,reactions:m.reactions})});
socket.on('delete_message',id=>{const m=db.messages.find(x=>x.id===Number(id));if(!m||m.sender_id!==uid)return;m.deleted=true;m.text='';m.file_url='';saveDb();io.to('conv:'+m.conversation_id).emit('message_deleted',m.id)});socket.on('call:offer',d=>{const to=Number(d.to);if(!safeUser(to))return;io.to('user:'+to).emit('call:offer',{from:uid,offer:d.offer,video:!!d.video});});
socket.on('call:answer',d=>{const to=Number(d.to);io.to('user:'+to).emit('call:answer',{from:uid,answer:d.answer});});
socket.on('call:ice',d=>{const to=Number(d.to);io.to('user:'+to).emit('call:ice',{from:uid,candidate:d.candidate});});
socket.on('call:end',d=>{const to=Number(d.to);io.to('user:'+to).emit('call:end',{from:uid});});
socket.join('user:'+uid);
socket.on('disconnect',()=>{const n=(online.get(uid)||1)-1;if(n<=0){online.delete(uid);io.emit('presence',{userId:uid,online:false})}else online.set(uid,n)})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));server.listen(PORT,()=>console.log(`Gish Chat running on http://localhost:${PORT}`));
