from pathlib import Path
p=Path('/mnt/data/zento_43123_work')
server=p/'server.js'; app=p/'public/app.js'; css=p/'public/style.css'; idx=p/'public/index.html'
s=server.read_text(); a=app.read_text(); c=css.read_text(); h=idx.read_text()
# schema for protected creator activity password
needle="  await q(`CREATE TABLE IF NOT EXISTS admin_audit_logs (id bigint generated by default as identity primary key, admin_user_id bigint, action text not null, target_id bigint, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now())`);"
insert="  await q(`CREATE TABLE IF NOT EXISTS admin_audit_logs (id bigint generated by default as identity primary key, admin_user_id bigint, action text not null, target_id bigint, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now())`);\n  await q(`CREATE TABLE IF NOT EXISTS creator_private_access(id INTEGER PRIMARY KEY DEFAULT 1,password_hash TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now())`);\n  const privateSeed=process.env.ZENTO_PRIVATE_ACTIVITY_PASSWORD||'1234';\n  const privateHash=await bcrypt.hash(String(privateSeed),12);\n  await q(`INSERT INTO creator_private_access(id,password_hash) VALUES(1,$1) ON CONFLICT(id) DO NOTHING`,[privateHash]);"
if needle in s: s=s.replace(needle,insert,1)
# protected activity endpoints: unlock + change password
needle="app.get('/api/admin/private-activity', auth, requireSuperAdmin, async(req,res)=>{try{"
if needle in s:
    pre="""app.post('/api/admin/private-activity/unlock', auth, requireSuperAdmin, async(req,res)=>{try{const pass=String(req.body?.password||'');if(!pass)return res.status(400).json({error:'رمز را وارد کنید'});const r=await q('SELECT password_hash FROM creator_private_access WHERE id=1');if(!r.rowCount||!(await bcrypt.compare(pass,r.rows[0].password_hash)))return res.status(401).json({error:'رمز نادرست است'});res.json({ok:true});}catch(e){res.status(500).json({error:'احراز هویت ناموفق بود'})}});
app.patch('/api/admin/private-activity/password', auth, requireSuperAdmin, async(req,res)=>{try{const oldPass=String(req.body?.currentPassword||''),newPass=String(req.body?.newPassword||'');if(newPass.length<4)return res.status(400).json({error:'رمز جدید حداقل ۴ کاراکتر باشد'});const r=await q('SELECT password_hash FROM creator_private_access WHERE id=1');if(!r.rowCount||!(await bcrypt.compare(oldPass,r.rows[0].password_hash)))return res.status(401).json({error:'رمز فعلی نادرست است'});const h=await bcrypt.hash(newPass,12);await q('UPDATE creator_private_access SET password_hash=$1,updated_at=now() WHERE id=1',[h]);await logAdmin(req.user.id,'change_private_activity_password',null,{});res.json({ok:true});}catch(e){res.status(500).json({error:'تغییر رمز ناموفق بود'})}});
"""
    s=s.replace(needle,pre+needle,1)
# add ICE config endpoint
needle="app.get('/api/calls/history', auth, (req,res,next)=>requireFeature('calls',req,res,next), async (req,res)=>"
if needle in s:
    pre="""app.get('/api/calls/ice-config', auth, (req,res)=>{const servers=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}];const urls=String(process.env.TURN_URLS||process.env.TURN_URL||'').split(',').map(x=>x.trim()).filter(Boolean);if(urls.length){servers.push({urls,username:String(process.env.TURN_USERNAME||''),credential:String(process.env.TURN_CREDENTIAL||'')})}res.json({iceServers:servers});});
"""
    s=s.replace(needle,pre+needle,1)
server.write_text(s)
# client: dynamic ICE config and wait for socket
old="const CALL_ICE=[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}];"
new="let CALL_ICE=[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302']}];\nasync function loadCallIce(){try{const d=await api('/api/calls/ice-config');if(Array.isArray(d.iceServers)&&d.iceServers.length)CALL_ICE=d.iceServers}catch{}}\nasync function ensureCallSocket(){if(socket?.connected)return true;try{connectSocket();await new Promise((resolve,reject)=>{let t=setTimeout(()=>reject(Error('اتصال پیام‌رسان آماده نیست')),7000);socket?.once('connect',()=>{clearTimeout(t);resolve()});socket?.once('connect_error',()=>{clearTimeout(t);reject(Error('اتصال تماس برقرار نشد'))})});return true}catch(e){showToast(e.message,true);return false}}"
a=a.replace(old,new,1)
# startCall: load ICE and socket first
old="async function startCall(video){if(me?.ban_until"
new="async function startCall(video){if(!(await ensureCallSocket()))return;await loadCallIce();if(me?.ban_until"
a=a.replace(old,new,1)
# incoming call load ICE
old="async function incomingCall(d){const u="
new="async function incomingCall(d){await loadCallIce();const u="
a=a.replace(old,new,1)
# call buttons: make labels and robust error handling
old="$('callAudio').onclick=()=>startCall(false);$('callVideo').onclick=()=>startCall(true);"
new="$('callAudio').onclick=()=>startCall(false);$('callVideo').onclick=()=>startCall(true);document.querySelectorAll('#callAudio,#callVideo').forEach(b=>b?.setAttribute('data-call-ready','1'));"
a=a.replace(old,new,1)
# Force desktop visible for direct chats in wrapper and ensure text labels
old="$('callAudio')?.classList.toggle('hidden',!!bot||!!protectedAdmin||!!me?.ban_until||current?.type==='group'||current?.type==='channel');$('callVideo')?.classList.toggle('hidden',!!bot||!!protectedAdmin||!!me?.ban_until||current?.type==='group'||current?.type==='channel');"
new="$('callAudio')?.classList.toggle('hidden',!!bot||!!protectedAdmin||!!me?.ban_until||current?.type!=='direct');$('callVideo')?.classList.toggle('hidden',!!bot||!!protectedAdmin||!!me?.ban_until||current?.type!=='direct');$('callAudio')?.setAttribute('title','تماس صوتی');$('callVideo')?.setAttribute('title','تماس تصویری');"
a=a.replace(old,new,1)
# Admin panel: add grouped private activity button and labels
old="<button data-sa-tab=\"calls\">📞 مرکز تماس</button><button data-sa-tab=\"support\">🎧 پشتیبانی</button>"
new="<button data-sa-tab=\"calls\">📞 مرکز تماس</button><button id=\"saPrivateActivityBtn\" class=\"sa-private-btn\">🔐 فعالیت خصوصی کاربران</button><button data-sa-tab=\"support\">🎧 پشتیبانی</button>"
a=a.replace(old,new,1)
# second nav too
old="<button data-sa-tab=\"calls\">📞 تماس‌ها</button><button data-sa-tab=\"support\">🎧 پشتیبانی</button>"
new="<button data-sa-tab=\"calls\">📞 تماس‌ها</button><button id=\"saPrivateActivityBtn2\" class=\"sa-private-btn\">🔐 فعالیت خصوصی</button><button data-sa-tab=\"support\">🎧 پشتیبانی</button>"
a=a.replace(old,new,1)
# Insert handler after main admin bindings near saRefreshAll
needle="$('saRefreshAll').onclick=()=>renderSuperAdminTab(currentAdminTab||'overview');"
if needle in a:
    code="""\n  const openPrivateActivity=async()=>{const v=await saDialog('🔐 فعالیت خصوصی کاربران',[{label:'رمز دسترسی سازنده',type:'password',placeholder:'رمز دسترسی را وارد کنید'}]);if(!v)return;try{await api('/api/admin/private-activity/unlock',{method:'POST',body:JSON.stringify({password:v[0]})});const d=await api('/api/admin/private-activity');const calls=d.calls||[],chats=d.chats||[];const change=await saDialog('🔑 تنظیم رمز فعالیت خصوصی',[{label:'رمز فعلی',type:'password'},{label:'رمز جدید',type:'password',placeholder:'حداقل ۴ کاراکتر'}]);if(change&&change[1]){try{await api('/api/admin/private-activity/password',{method:'PATCH',body:JSON.stringify({currentPassword:change[0],newPassword:change[1]})});showToast('رمز فعالیت خصوصی تغییر کرد ✓')}catch(e){showToast(e.message,true)}}openModal('فعالیت خصوصی کاربران',`<div class=\"private-activity-panel\"><div class=\"private-activity-hero\"><span>🔐</span><div><b>مرکز خصوصی سازنده</b><small>تاریخچه تماس‌ها و آمار گفتگوها فقط برای سازنده</small></div></div><div class=\"private-activity-grid\"><section><h4>📞 تماس‌ها (${calls.length})</h4>${calls.map(x=>`<article><b>${esc(x.caller_name||'-')} → ${esc(x.receiver_name||'-')}</b><small>${esc(x.type||'audio')} · ${esc(x.status||'-')} · ${Number(x.duration||0)} ثانیه</small></article>`).join('')||'<div class=\"empty\">تماسی ثبت نشده.</div>'}</section><section><h4>💬 گفتگوها (${chats.length})</h4>${chats.map(x=>`<article><b>${esc(x.name||'گفتگو')}</b><small>${Number(x.members||0)} عضو · ${Number(x.messages||0)} پیام</small></article>`).join('')||'<div class=\"empty\">گفتگویی ثبت نشده.</div>'}</section></div></div>`,async()=>{});$('modalOk').classList.add('hidden');$('modalCancel').textContent='بستن';}catch(e){showToast(e.message,true)}};\n  $('saPrivateActivityBtn')?.addEventListener('click',openPrivateActivity);$('saPrivateActivityBtn2')?.addEventListener('click',openPrivateActivity);\n"""
    a=a.replace(needle,needle+code,1)
# The above handler insertion may not match; add a delegated fallback before renderSuperAdminTab definition
if 'const openPrivateActivity=async()=>{' not in a:
    marker="function renderSuperAdminTab(tab){"
    code="""async function openCreatorPrivateActivity(){const v=await saDialog('🔐 فعالیت خصوصی کاربران',[{label:'رمز دسترسی سازنده',type:'password',placeholder:'رمز را وارد کنید'}]);if(!v)return;try{await api('/api/admin/private-activity/unlock',{method:'POST',body:JSON.stringify({password:v[0]})});const d=await api('/api/admin/private-activity');openModal('🔐 فعالیت خصوصی کاربران',`<div class=\"private-activity-panel\"><div class=\"private-activity-hero\"><span>🔐</span><div><b>مرکز خصوصی سازنده</b><small>فقط سازنده می‌تواند این اطلاعات را مشاهده کند。</small></div></div><div class=\"private-activity-grid\"><section><h4>📞 تماس‌ها</h4>${(d.calls||[]).map(x=>`<article><b>${esc(x.caller_name||'-')} → ${esc(x.receiver_name||'-')}</b><small>${esc(x.type||'audio')} · ${esc(x.status||'-')} · ${Number(x.duration||0)} ثانیه</small></article>`).join('')||'<div class=\"empty\">تماسی ثبت نشده.</div>'}</section><section><h4>💬 گفتگوها</h4>${(d.chats||[]).map(x=>`<article><b>${esc(x.name||'گفتگو')}</b><small>${Number(x.members||0)} عضو · ${Number(x.messages||0)} پیام</small></article>`).join('')||'<div class=\"empty\">گفتگویی ثبت نشده.</div>'}</section></div><button id=\"changePrivateActivityPassword\" class=\"secondary full\">🔑 تغییر رمز</button></div>`,async()=>{});$('modalOk').classList.add('hidden');$('modalCancel').textContent='بستن';$('changePrivateActivityPassword').onclick=async()=>{const x=await saDialog('تغییر رمز فعالیت خصوصی',[{label:'رمز فعلی',type:'password'},{label:'رمز جدید',type:'password'}]);if(!x||!x[1])return;try{await api('/api/admin/private-activity/password',{method:'PATCH',body:JSON.stringify({currentPassword:x[0],newPassword:x[1]})});showToast('رمز تغییر کرد ✓')}catch(e){showToast(e.message,true)}}}catch(e){showToast(e.message,true)}}\n"""
    a=a.replace(marker,code+marker,1)
# add delegated click in document body for buttons
marker="document.addEventListener('click',e=>{"
# avoid complex if exists, use window event once near app end
if 'data-private-activity' not in a:
    a += "\n\n// v4.31.24 creator private activity fallback\ndocument.addEventListener('click',e=>{const b=e.target.closest('#saPrivateActivityBtn,#saPrivateActivityBtn2');if(b){e.preventDefault();openCreatorPrivateActivity()}});\n"
# upload progress: replace uploadPendingAttachments with overall weighted progress
start=a.find('async function uploadPendingAttachments(){')
end=a.find('\nfunction cleanupRecorderPreview',start)
if start!=-1 and end!=-1:
    fn="""async function uploadPendingAttachments(){
  if(!current||!pendingAttachments.length)return;
  const list=[...pendingAttachments];const queue=[...list];const results=[];const state=new Map(list.map(x=>[x,{loaded:0,total:x.file.size}]));
  showUploadHUD(`آپلود ${list.length} فایل`);
  const render=()=>{let loaded=0,total=0;state.forEach(v=>{loaded+=v.loaded;total+=v.total});updateUploadHUD(loaded,total);$('zentoUploadMeta')&&($('zentoUploadMeta').textContent=`${list.length} فایل · ${(loaded/1024/1024).toFixed(1)} / ${(total/1024/1024).toFixed(1)} MB`)};
  const worker=async()=>{while(queue.length){const x=queue.shift();const fd=new FormData();fd.append('file',x.file,x.file.name);const u=await uploadWithProgress('/api/upload',fd,(l,t)=>{state.set(x,{loaded:l,total:t||x.file.size});render()});results.push({x,u});}};
  try{await Promise.all([worker(),worker(),worker()]);for(const {x,u} of results){const out=await api('/api/messages',{method:'POST',body:JSON.stringify({conversationId:current.id,text:x.caption||'',fileUrl:u.url,fileType:u.mime,fileName:u.name,kind:x.kind,profileId:stage1ProfileByConv[current.id]||stage1ProfileByConv._default})});appendMessage(out)}hideUploadHUD();scrollBottom();closeAttachComposer();$('file').value='';}
  catch(e){hideUploadHUD();showToast(e.message||'آپلود ناموفق بود',true)}
}
"""
    a=a[:start]+fn+a[end:]
# attachment editor: allow audio/file metadata edit
old="const edit=['image','gif','video'].includes(x.kind)?`<button class=\"attachment-edit\" data-edit-i=\"${i}\">✏️ ویرایش</button>`:'';"
new="const edit=`<button class=\"attachment-edit\" data-edit-i=\"${i}\">✏️ ویرایش</button>`;"
a=a.replace(old,new,1)
# openMediaEditor broaden and generic modal for audio/file
old="function openMediaEditor(i){makeAttachmentEditorShell();const x=pendingAttachments[i];if(!x||!['image','gif','video'].includes(x.kind))return;"
new="function openMediaEditor(i){makeAttachmentEditorShell();const x=pendingAttachments[i];if(!x)return;if(!['image','gif','video'].includes(x.kind)){const v=prompt('نام فایل / کپشن',x.caption||x.file.name);if(v!==null){x.caption=v.trim();renderAttachmentPreview()}return;}"
a=a.replace(old,new,1)
# group/channel ensure visible inline submit button as fallback, and callback bind
old="</div></div>`,async()=>{const members="
new="</div><button type=\"button\" class=\"create-inline-submit primary\" id=\"createGroupInline\">✓ ساخت گروه</button></div>`,async()=>{const members="
a=a.replace(old,new,1)
old="</div>`,async()=>{try{let photo='';"
new="</div><button type=\"button\" class=\"create-inline-submit primary\" id=\"createChannelInline\">✓ ساخت کانال</button></div>`,async()=>{try{let photo='';"
a=a.replace(old,new,1)
# After modalOk lines add inline click trigger
old="$('modalOk').textContent='ساخت گروه';$('modalOk').classList.remove('hidden');$('newPhoto')?.addEventListener"
new="$('modalOk').textContent='✓ ساخت گروه';$('modalOk').classList.remove('hidden');$('createGroupInline')?.addEventListener('click',()=>$('modalOk').click());$('newPhoto')?.addEventListener"
a=a.replace(old,new,1)
old="$('modalOk').textContent='ساخت کانال';$('modalOk').classList.remove('hidden');$('newPhoto')?.addEventListener"
new="$('modalOk').textContent='✓ ساخت کانال';$('modalOk').classList.remove('hidden');$('createChannelInline')?.addEventListener('click',()=>$('modalOk').click());$('newPhoto')?.addEventListener"
a=a.replace(old,new,1)
# first openUserProfile add report button in profile actions if absent
old="<div class=\"profile-actions\"><button id=\"startDirect\" class=\"primary\">💬 پیام</button><button id=\"blockOther\" class=\"danger\">"
new="<div class=\"profile-actions\"><button id=\"startDirect\" class=\"primary\">💬 پیام</button><button id=\"reportOther\" class=\"danger\">🚨 گزارش کاربر</button><button id=\"blockOther\" class=\"danger\">"
a=a.replace(old,new,1)
# story list professional markup
old="const cards=groups.map(g=>`<button class=\"story-person ${g.has_unseen?'unseen':''}\" data-story-user=\"${g.user_id}\">${storyRing(g)}<span><b>${esc(g.display_name)}</b><small>${g.stories.length} استوری</small></span></button>`).join('');"
new="const cards=groups.map(g=>`<button class=\"story-person-pro ${g.has_unseen?'unseen':''}\" data-story-user=\"${g.user_id}\"><div class=\"story-person-pro-ring\">${storyRing(g)}</div><span><b>${esc(g.display_name)}</b><small>${g.stories.length} استوری · ${g.has_unseen?'جدید':'مشاهده‌شده'}</small></span><i>›</i></button>`).join('');"
a=a.replace(old,new,1)
# version
(p/'VERSION.txt').write_text('4.31.24\n')
import json
pkg=json.loads((p/'package.json').read_text());pkg['version']='4.31.24';(p/'package.json').write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n')
# cache bump
h=h.replace('app.js?v=116','app.js?v=117').replace('app.js?v=115','app.js?v=117')
c=c.replace('v4.31.23','v4.31.24')
# append CSS
c += r'''
/* ===== ZENTO v4.31.24 — creator admin, stories, upload confirm, call reliability ===== */
.sa-private-btn{background:linear-gradient(135deg,rgba(255,180,70,.16),rgba(239,77,184,.12))!important;border-color:rgba(255,190,90,.25)!important;color:#ffd98a!important;font-weight:900!important}
.sa-quick,.sa-tabs{scrollbar-width:thin}.sa-quick button,.sa-tabs button{position:relative}.sa-quick button:after,.sa-tabs button:after{content:'';display:block;height:2px;width:0;margin-top:5px;background:linear-gradient(90deg,#39d7ff,#ff4db8);transition:.2s}.sa-quick button:hover:after,.sa-tabs button:hover:after{width:100%}
.private-activity-panel{display:grid;gap:14px}.private-activity-hero{display:flex;align-items:center;gap:12px;padding:16px;border-radius:18px;color:#fff;background:linear-gradient(135deg,#101c35,#3d4f9c,#9a3f9d)}.private-activity-hero>span{width:48px;height:48px;border-radius:15px;display:grid;place-items:center;background:rgba(255,255,255,.14);font-size:23px}.private-activity-hero b,.private-activity-hero small{display:block}.private-activity-hero small{font-size:9px;opacity:.75;margin-top:4px}.private-activity-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.private-activity-grid section{padding:13px;border:1px solid var(--line);border-radius:18px;background:var(--panel2)}.private-activity-grid h4{margin:0 0 8px}.private-activity-grid article{padding:9px;border-radius:12px;background:var(--panel);margin:6px 0}.private-activity-grid article b,.private-activity-grid article small{display:block}.private-activity-grid article small{color:var(--muted);font-size:9px;margin-top:3px}
.story-person-pro{width:100%;display:flex;align-items:center;gap:12px;padding:12px;border:1px solid var(--line);background:var(--panel2);border-radius:18px;text-align:right;color:var(--text);transition:.2s}.story-person-pro:hover{transform:translateY(-2px);border-color:#8abff3;box-shadow:0 12px 30px rgba(51,144,236,.12)}.story-person-pro-ring{width:62px;height:62px;padding:3px;border-radius:50%;background:linear-gradient(135deg,#39d7ff,#7b61ff,#ff4db8);flex:0 0 62px}.story-person-pro-ring>*{width:100%;height:100%}.story-person-pro>span{min-width:0;flex:1}.story-person-pro b,.story-person-pro small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.story-person-pro small{color:var(--muted);font-size:9px;margin-top:4px}.story-person-pro i{font-style:normal;font-size:26px;color:var(--muted)}.story-person-pro.unseen{background:linear-gradient(135deg,rgba(51,144,236,.10),rgba(239,77,184,.08))}.create-inline-submit{width:100%;margin-top:14px;padding:13px!important;border-radius:15px!important;font-size:12px!important}.attachment-preview-item{position:relative}.attachment-edit{position:absolute;right:8px;bottom:8px;z-index:3;padding:7px 10px;border-radius:10px;background:rgba(10,18,30,.82);color:#fff;font-size:9px;border:1px solid rgba(255,255,255,.15)}.attachment-edit:hover{background:linear-gradient(135deg,#3390ec,#7b61ff)}
#callAudio[data-call-ready="1"],#callVideo[data-call-ready="1"]{visibility:visible}.call-card-modern video{background:#05070b}.call-card-modern .call-status-dot{animation:pulseCall 1.6s infinite}@keyframes pulseCall{50%{box-shadow:0 0 0 9px rgba(51,144,236,0)}}
@media(max-width:850px){.private-activity-grid{grid-template-columns:1fr}.sa-quick,.sa-tabs{padding-bottom:6px}.sa-quick button,.sa-tabs button{font-size:10px}.create-inline-submit{font-size:11px!important}}
'''
css.write_text(c)
idx.write_text(h)
app.write_text(a)
