from pathlib import Path
import re
root=Path('/mnt/data/zento_43122_work')
app=root/'public/app.js'; s=app.read_text()
# header icon-only
s=s.replace('<button class="head-btn labeled-head" id="chatSearch">⌕ <span>جستجو</span></button><button class="head-btn labeled-head" id="callAudio" title="تماس صوتی">📞 <span>تماس صوتی</span></button><button class="head-btn labeled-head" id="callVideo" title="تماس تصویری">📹 <span>تماس تصویری</span></button>', '<button class="head-btn labeled-head chat-head-icon" id="chatSearch" title="جستجو در گفتگو" aria-label="جستجو در گفتگو">⌕</button><button class="head-btn labeled-head chat-head-icon" id="callAudio" title="تماس صوتی" aria-label="تماس صوتی">📞</button><button class="head-btn labeled-head chat-head-icon" id="callVideo" title="تماس تصویری" aria-label="تماس تصویری">📹</button>',1)
# upload HUD speed
old="el.innerHTML='<div class=\"zento-upload-hud-icon\">⬆</div><div class=\"zento-upload-hud-copy\"><b id=\"zentoUploadTitle\">در حال آپلود</b><small id=\"zentoUploadMeta\">آماده‌سازی…</small><div class=\"zento-upload-track\"><i id=\"zentoUploadBar\"></i></div></div><strong id=\"zentoUploadPercent\">0%</strong>';"
new="el.innerHTML='<div class=\"zento-upload-hud-icon\">⬆</div><div class=\"zento-upload-hud-copy\"><b id=\"zentoUploadTitle\">در حال آپلود</b><small id=\"zentoUploadMeta\">آماده‌سازی…</small><div class=\"zento-upload-track\"><i id=\"zentoUploadBar\"></i></div></div><div class=\"zento-upload-hud-stats\"><strong id=\"zentoUploadPercent\">0%</strong><small id=\"zentoUploadSpeed\">0 MB/s</small></div>';"
s=s.replace(old,new,1)
s=s.replace("function showUploadHUD(title='در حال آپلود'){const el=ensureUploadHUD();el.classList.remove('hidden');$('zentoUploadTitle').textContent=title;$('zentoUploadMeta').textContent='در حال ارسال فایل…';$('zentoUploadBar').style.width='0%';$('zentoUploadPercent').textContent='0%';}","function showUploadHUD(title='در حال آپلود'){const el=ensureUploadHUD();el.classList.remove('hidden');el.classList.remove('done');$('zentoUploadTitle').textContent=title;$('zentoUploadMeta').textContent='در حال ارسال فایل…';$('zentoUploadBar').style.width='0%';$('zentoUploadPercent').textContent='0%';if($('zentoUploadSpeed'))$('zentoUploadSpeed').textContent='0 MB/s';window.__zentoUploadTick=null;}",1)
pattern=r"function updateUploadHUD\(loaded,total\)\{.*?\}\nfunction hideUploadHUD"
replacement="function updateUploadHUD(loaded,total){const p=total?Math.min(100,Math.round(loaded/total*100)):0;$('zentoUploadBar')?.style.setProperty('width',p+'%');if($('zentoUploadPercent'))$('zentoUploadPercent').textContent=p+'%';if($('zentoUploadMeta'))$('zentoUploadMeta').textContent=total?`${(loaded/1024/1024).toFixed(1)} / ${(total/1024/1024).toFixed(1)} MB`:'در حال ارسال…';const now=performance.now();if($('zentoUploadSpeed')){if(window.__zentoUploadTick){const dt=Math.max(1,now-window.__zentoUploadTick.t);const db=Math.max(0,loaded-window.__zentoUploadTick.b);const speed=db/1024/1024/(dt/1000);$('zentoUploadSpeed').textContent=(speed>=1?speed.toFixed(1):speed.toFixed(2))+' MB/s';}window.__zentoUploadTick={t:now,b:loaded};}}\nfunction hideUploadHUD"
s,n=re.subn(pattern,replacement,s,count=1)
if n!=1: print('upload function replacement failed',n)
# Replace search function
start=s.index('async function stage2SearchDialog(){'); end=s.index('\n\nconst UI_LANG_KEY',start)
newfunc=r'''async function stage2SearchDialog(){
  if(!current)return showToast('اول یک گفتگو را انتخاب کن',true);
  openModal('🔎 جستجوی پیشرفته در گفتگو',`<div class="s2-search s2-search-pro"><div class="s2-search-hero"><div class="s2-search-icon">⌕</div><div><b>جستجوی هوشمند گفتگو</b><small>پیام، رسانه، فرستنده و بازه زمانی را سریع پیدا کن.</small></div><span>FAST</span></div><div class="s2-search-main"><div class="s2-search-input-wrap"><span>⌕</span><input id="s2q" placeholder="مثلاً سلام، فایل، عکس یا لینک…" autofocus><button id="s2clear" type="button">×</button></div><div class="s2-filter-chips"><button class="active" data-s2-chip="all">همه</button><button data-s2-chip="image">📷 عکس</button><button data-s2-chip="video">🎥 ویدیو</button><button data-s2-chip="audio">🎵 صوت</button><button data-s2-chip="file">📄 فایل</button><button data-s2-chip="link">🔗 لینک</button></div><div class="s2-filters"><label>از<input id="s2from" type="date"></label><label>تا<input id="s2to" type="date"></label><button id="s2go" class="primary">⌕ جستجو</button></div></div><div class="s2-results-head"><b>نتایج</b><small id="s2count">آماده جستجو</small></div><div id="s2results" class="s2-results"><div class="s2-empty"><span>⌕</span><b>دنبال چه چیزی می‌گردی؟</b><small>عبارت یا فیلتر را انتخاب کن.</small></div></div></div>`,()=>{});
  $('modalOk').classList.add('hidden');$('modalCancel').textContent='بستن';let type='all';
  document.querySelectorAll('[data-s2-chip]').forEach(b=>b.onclick=()=>{type=b.dataset.s2Chip;document.querySelectorAll('[data-s2-chip]').forEach(x=>x.classList.toggle('active',x===b));});
  $('s2clear').onclick=()=>{$('s2q').value='';$('s2q').focus()};
  const run=async()=>{const qv=$('s2q').value.trim();const params=new URLSearchParams({q:qv,type});if($('s2from').value)params.set('from',$('s2from').value);if($('s2to').value){const d=new Date($('s2to').value);d.setDate(d.getDate()+1);params.set('to',d.toISOString())}try{const r=await api(`/api/conversations/${current.id}/search?${params}`);$('s2count').textContent=`${r.length} نتیجه`;$('s2results').innerHTML=r.length?r.map(m=>`<button class="search-result s2-result-pro" data-s2msg="${m.id}"><span class="s2-result-type">${m.kind==='image'?'📷':m.kind==='video'?'🎥':m.kind==='audio'||m.kind==='voice'?'🎵':'📄'}</span><span class="s2-result-copy"><b>${esc(m.display_name||m.username||'کاربر')}</b><small>${new Date(m.created_at).toLocaleString('fa-IR')}</small><div>${m.text?formatText(m.text):esc(m.kind==='voice'?'پیام صوتی':m.file_name||'فایل')}</div></span><i>‹</i></button>`).join(''):'<div class="s2-empty"><span>⌕</span><b>نتیجه‌ای پیدا نشد</b><small>فیلتر یا عبارت دیگری امتحان کن.</small></div>';document.querySelectorAll('[data-s2msg]').forEach(x=>x.onclick=()=>{const id=Number(x.dataset.s2msg);$('modal').classList.add('hidden');const row=document.querySelector(`[data-msg="${id}"]`);if(row){row.scrollIntoView({behavior:'smooth',block:'center'});row.classList.add('stage2-highlight');setTimeout(()=>row.classList.remove('stage2-highlight'),1800)}else showToast('پیام پیدا شد؛ برای نمایش آن گفتگو را باز کن')})}catch(e){$('s2count').textContent='خطا';$('s2results').innerHTML=`<div class="s2-empty error"><span>!</span><b>جستجو ناموفق بود</b><small>${esc(e.message)}</small></div>`}};
  $('s2go').onclick=run;$('s2q').onkeydown=e=>{if(e.key==='Enter')run()};
}'''
s=s[:start]+newfunc+s[end:]
# Replace newGroup/newChannel whole functions
st=s.index('async function newGroup(){'); en=s.index('\nfunction openModal',st)
newgc=r'''async function newGroup(){const users=await api('/api/users');openModal('✨ ساخت گروه حرفه‌ای',`<div class="create-social-pro"><div class="create-social-hero group"><div class="create-social-icon">👥</div><div><b>گروه جدید زنتو</b><small>یک فضای خصوصی برای گفتگو، فایل، تماس و کنفرانس بساز.</small></div></div><div class="create-social-avatar-row"><div><b>عکس گروه</b><small>تصویر گروه را انتخاب کن.</small></div><input id="newPhoto" type="file" accept="image/*"><div id="newPhotoPreview" class="create-photo-preview">👥</div></div><div class="create-social-grid"><label>نام گروه<input id="newName" placeholder="مثلاً دوستان دانشگاه"></label><label>شناسه عمومی<input id="newUsername" placeholder="my_group"></label></div><label>توضیحات<textarea id="newDesc" placeholder="گروه درباره چیست؟"></textarea></label><div class="create-social-title"><b>اعضای اولیه</b><small>حداقل یک نفر دیگر انتخاب کن</small></div><div class="pick-users premium-picks">${users.map(u=>`<label class="pick premium-pick"><input type="checkbox" value="${u.id}"><span>${avatar(u,'avatar tiny-avatar')}</span><span><b>${esc(u.display_name)}</b><small>@${esc(u.username)}</small></span><i>✓</i></label>`).join('')}</div></div>`,async()=>{const members=[...document.querySelectorAll('.pick input:checked')].map(x=>Number(x.value));if(!members.length)return showToast('حداقل یک عضو دیگر انتخاب کن',true);try{let photo='';const f=$('newPhoto')?.files?.[0];if(f){const fd=new FormData();fd.append('file',f,f.name);showUploadHUD('آپلود عکس گروه');const up=await uploadWithProgress('/api/upload',fd,updateUploadHUD);hideUploadHUD();photo=up.url}const c=await api('/api/conversations/group',{method:'POST',body:JSON.stringify({name:$('newName').value,username:$('newUsername').value,description:$('newDesc').value,members,photo})});closeModal();await loadConvs();openConv(c.id)}catch(e){hideUploadHUD();showToast(e.message,true)}});$('modalOk').textContent='ساخت گروه';$('modalOk').classList.remove('hidden');$('newPhoto')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f&&$('newPhotoPreview'))$('newPhotoPreview').innerHTML=`<img src="${URL.createObjectURL(f)}">`})}
async function newChannel(){openModal('📢 ساخت کانال حرفه‌ای',`<div class="create-social-pro"><div class="create-social-hero channel"><div class="create-social-icon">📢</div><div><b>کانال جدید زنتو</b><small>محتوای رسمی، اطلاعیه، فیلم، خبر و پست‌های خودت را منتشر کن.</small></div></div><div class="create-social-avatar-row"><div><b>عکس کانال</b><small>پوستر یا لوگوی کانال را انتخاب کن.</small></div><input id="newPhoto" type="file" accept="image/*"><div id="newPhotoPreview" class="create-photo-preview">📢</div></div><div class="create-social-grid"><label>نام کانال<input id="newName" placeholder="کانال زنتو"></label><label>شناسه عمومی<input id="newUsername" placeholder="zento_news"></label></div><label>توضیحات<textarea id="newDesc" placeholder="موضوع و توضیحات کانال"></textarea></label><div class="create-channel-features"><span>✓ پست و رسانه</span><span>✓ آمار بازدید</span><span>✓ لینک عمومی</span><span>✓ مدیریت اعضا</span></div></div>`,async()=>{try{let photo='';const f=$('newPhoto')?.files?.[0];if(f){const fd=new FormData();fd.append('file',f,f.name);showUploadHUD('آپلود عکس کانال');const up=await uploadWithProgress('/api/upload',fd,updateUploadHUD);hideUploadHUD();photo=up.url}const c=await api('/api/conversations/channel',{method:'POST',body:JSON.stringify({name:$('newName').value,username:$('newUsername').value,description:$('newDesc').value,photo})});closeModal();await loadConvs();openConv(c.id)}catch(e){hideUploadHUD();showToast(e.message,true)}});$('modalOk').textContent='ساخت کانال';$('modalOk').classList.remove('hidden');$('newPhoto')?.addEventListener('change',e=>{const f=e.target.files?.[0];if(f&&$('newPhotoPreview'))$('newPhotoPreview').innerHTML=`<img src="${URL.createObjectURL(f)}">`})}
'''
s=s[:st]+newgc+s[en:]
# archive hero
s=s.replace('<div class="archive-hero"><b>🗃️ بایگانی پیشرفته</b><small>${archived.length} گفتگوی بایگانی‌شده · گفتگوها از صفحه اصلی مخفی هستند اما حذف نشده‌اند.</small></div><input id="archiveSearch" class="archive-search" placeholder="جستجو در بایگانی…">', '<div class="archive-hero archive-hero-pro"><div class="archive-hero-icon">🗃️</div><div><span>PRIVATE SPACE</span><b>بایگانی هوشمند گفتگوها</b><small>${archived.length} گفتگوی بایگانی‌شده · گفتگوها امن و قابل بازیابی هستند.</small></div><strong>${archived.length}</strong></div><div class="archive-toolbar"><span>↕ مرتب‌سازی هوشمند</span><input id="archiveSearch" class="archive-search" placeholder="جستجو در بایگانی…"></div>',1)
# profile preview
s=s.replace('<div class="profile-preview"><button id="profileAvatarBtn" class="avatar huge">گ</button><div><b id="profileUser"></b><small>برای تغییر عکس روی تصویر بزن</small></div></div>', '<div class="profile-preview profile-preview-pro"><div class="profile-cover-glow"></div><button id="profileAvatarBtn" class="avatar huge">گ</button><div class="profile-preview-copy"><span>MY ZENTO IDENTITY</span><b id="profileUser"></b><small>پروفایل، گالری و هویت دیجیتال خودت را مدیریت کن.</small></div></div>',1)
app.write_text(s)

sv=root/'server.js'; s=sv.read_text()
s=s.replace("description: c.description || '', username: c.username || '', verified: !!c.verified, unread_count", "description: c.description || '', username: c.username || '', photo: c.photo || '', verified: !!c.verified, unread_count",1)
s=s.replace("INSERT INTO conversations(name,type,owner_id,username,description) VALUES($1,'group',$2,$3,$4)", "INSERT INTO conversations(name,type,owner_id,username,description,photo) VALUES($1,'group',$2,$3,$4,$5)",1)
s=s.replace("[name, req.user.id, username || null, String(req.body.description || '').trim().slice(0, 200)]", "[name, req.user.id, username || null, String(req.body.description || '').trim().slice(0, 200), String(req.body.photo || '').slice(0,1000)]",1)
s=s.replace("INSERT INTO conversations(name,type,owner_id,username,description) VALUES($1,'channel',$2,$3,$4)", "INSERT INTO conversations(name,type,owner_id,username,description,photo) VALUES($1,'channel',$2,$3,$4,$5)",1)
s=s.replace("[name, req.user.id, username, description]);", "[name, req.user.id, username, description, String(req.body.photo || '').slice(0,1000)]);",1)
s=s.replace("app.get('/api/admin/conversations', auth, requireAnyAdmin, async(req,res)=>", "app.get('/api/admin/conversations', auth, requireSuperAdmin, async(req,res)=>",1)
s=s.replace("const calls=await adminQuery(`SELECT c.id,c.status,c.duration,c.created_at,c.type,cu.display_name caller_name,ru.display_name receiver_name FROM calls c LEFT JOIN users cu ON cu.id=c.caller_id LEFT JOIN users ru ON ru.id=c.receiver_id ORDER BY c.id DESC LIMIT 30`);", "const calls=(req.user?.role==='superadmin')?await adminQuery(`SELECT c.id,c.status,c.duration,c.created_at,c.type,cu.display_name caller_name,ru.display_name receiver_name FROM calls c LEFT JOIN users cu ON cu.id=c.caller_id LEFT JOIN users ru ON ru.id=c.receiver_id ORDER BY c.id DESC LIMIT 30`):{rows:[]};",1)
needle="await q(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}'::jsonb`);"
s=s.replace(needle,needle+"\n  await q(`ALTER TABLE conversations ADD COLUMN IF NOT EXISTS photo TEXT NOT NULL DEFAULT ''`);",1)
marker="app.get('/api/admin/health', auth, requireAnyAdmin, async (_req,res)=>{"
insert="""app.get('/api/admin/private-activity', auth, requireSuperAdmin, async(req,res)=>{try{const calls=await q(`SELECT c.id,c.type,c.status,c.duration,c.created_at,cu.id caller_id,cu.display_name caller_name,cu.username caller_username,ru.id receiver_id,ru.display_name receiver_name,ru.username receiver_username FROM calls c LEFT JOIN users cu ON cu.id=c.caller_id LEFT JOIN users ru ON ru.id=c.receiver_id ORDER BY c.created_at DESC LIMIT 200`);const chats=await q(`SELECT c.id,c.type,c.name,c.username,c.created_at,c.updated_at,COUNT(DISTINCT cm.user_id)::int members,(SELECT COUNT(*)::int FROM messages m WHERE m.conversation_id=c.id AND m.deleted=false) messages FROM conversations c LEFT JOIN conversation_members cm ON cm.conversation_id=c.id GROUP BY c.id ORDER BY c.updated_at DESC LIMIT 200`);res.json({calls:calls.rows.map(x=>({...x,id:Number(x.id),duration:Number(x.duration||0),caller_id:x.caller_id?Number(x.caller_id):null,receiver_id:x.receiver_id?Number(x.receiver_id):null})),chats:chats.rows.map(x=>({...x,id:Number(x.id),members:Number(x.members||0),messages:Number(x.messages||0)}))})}catch(e){console.error('private activity',e);res.status(500).json({error:'دریافت فعالیت خصوصی ناموفق بود'})}});\n"""
s=s.replace(marker,insert+marker,1)
sv.write_text(s)

sp=root/'supabase/schema.sql'; s=sp.read_text(); s=s.replace("description text not null default '',\n  created_at", "description text not null default '',\n  photo text not null default '',\n  created_at",1); sp.write_text(s)
