-- Zento v4.28: site admin roles, audit logs, bans, reports, live support threads
ALTER TABLE users ADD COLUMN IF NOT EXISTS ban_until timestamptz;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ban_reason text;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS message_id bigint REFERENCES messages(id) ON DELETE CASCADE;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'open';
CREATE INDEX IF NOT EXISTS reports_status_created_idx ON reports(status,created_at DESC);
CREATE TABLE IF NOT EXISTS site_admins (
  user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'support',
  permissions jsonb NOT NULL DEFAULT '{}'::jsonb,
  active boolean NOT NULL DEFAULT true,
  created_by bigint,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id bigint,
  action text NOT NULL,
  target_id bigint,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS admin_audit_created_idx ON admin_audit_logs(created_at DESC);
ALTER TABLE support_requests ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'open';
ALTER TABLE support_requests ADD COLUMN IF NOT EXISTS closed_at timestamptz;
ALTER TABLE support_requests ADD COLUMN IF NOT EXISTS closed_by bigint;
CREATE TABLE IF NOT EXISTS support_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_id bigint NOT NULL REFERENCES support_requests(id) ON DELETE CASCADE,
  sender_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  text text NOT NULL,
  is_admin boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS support_messages_support_idx ON support_messages(support_id,created_at);
