const $=id=>document.getElementById(id);
let token=localStorage.getItem('gish_token'),me=null,convs=[],current=null,socket=null,typingTimer=null,recording=null,recordChunks=[],replyTo=null,messageCache={};
const emojis=['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😇','🙂','🙃','😉','😌','😍','🥰','😘','😎','🤩','🥳','🤔','🤭','🤫','🫡','😴','😮','😲','😢','😭','😡','🤬','🤯','😱','😶','🙄','😏','😅','🤗','🫠','👍','👎','👏','🙌','🙏','💪','🤝','✌️','👌','❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','🔥','✨','⭐','🌟','💯','🎉','🎊','🚀','🎯','💡','📌','📢','👥','💬','🎙️','🎵','🎬','📎','🌈','☀️','🌙','🍕','🍔','🍟','🍰','☕','⚽','🏀','🎮','🎧','🎸','🐱','🐶','🦊','🐼','🌹','🎁','💎','🧠','⚡','💫','🫶','👀'];
function api(url,opt={}){opt.headers={...(opt.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};return fetch(url,opt).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'خطا');return d})}
function showAuth(){$('auth').classList.remove('hidden');$('app').classList.add('hidden')}function showApp(){$('auth').classList.add('hidden');$('app').classList.remove('hidden')}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function avatarHTML(u,cls='avatar'){return u?.avatar?`<div class="${cls}"><img src="${esc(u.avatar)}" alt=""></div>`:`<div class="${cls}">${esc((u?.display_name||'گ')[0])}</div>`}
function setMyAvatar(u){$('myAvatarText').parentElement.innerHTML=u.avatar?`<img src="${esc(u.avatar)}" alt="">`:`<span id="myAvatarText">${esc((u.display_name||'گ')[0])}</span>`;$('profileAvatarText').parentElement.innerHTML=u.avatar?`<img src="${esc(u.avatar)}" alt="">`:`<span id="profileAvatarText">${esc((u.display_name||'گ')[0])}</span>`}
async function boot(){if(!token)return showAuth();try{me=await api('/api/me');showApp();refreshDrawerProfile();setMyAvatar(me);socket=io({auth:{token},reconnection:true});installCallHandlers();socket.on('connect_error',err=>console.warn('Gish socket:',err.message));socket.on('message',m=>{messageCache[m.id]=m;if(current&&m.conversation_id===current.id)renderMessage(m);loadConvs()});socket.on('reaction',d=>{const el=document.querySelector(`[data-msg="${d.messageId}"]`);if(el)updateReactions(el,d.reactions)});socket.on('message_deleted',id=>{document.querySelector(`[data-msg="${id}"]`)?.remove();delete messageCache[id]});socket.on('typing',d=>{if(current)$('typing').textContent=d.typing?'در حال نوشتن…':''});await loadConvs()}catch{localStorage.removeItem('gish_token');token=null;showAuth()}}
async function loadConvs(){
  convs=await api('/api/conversations');
  renderFilteredConvs();
}
function renderFilteredConvs(){
  const list=activeFilter==='all'?convs:convs.filter(c=>c.type===activeFilter);
  const chats=$('chats');
  chats.innerHTML=list.map(c=>{
    const other=c.type==='direct'?c.members.find(x=>Number(x.id)!==Number(me.id)):null;
    const title=c.type==='direct'?(other?.display_name||'گفتگو'):c.name;
    const icon=c.type==='channel'?'📢':c.type==='group'?'👥':'گ';
    return `<button type="button" class="chat-item ${current&&Number(current.id)===Number(c.id)?'active':''}" data-id="${c.id}">
      ${c.type==='direct'?avatarHTML(other):`<div class="avatar">${icon}</div>`}
      <div class="ci"><b>${esc(title)}</b><small>${c.type==='channel'?'کانال':c.type==='group'?`${c.members.length} عضو`:(other?'@'+esc(other.username):'گفتگوی خصوصی')} · ${esc(c.last_text||'')}</small></div>
      <span class="type-badge">${c.type==='channel'?'کانال':c.type==='group'?'گروه':'خصوصی'}</span>
    </button>`;
  }).join('')||'<div class="empty">گفتگویی پیدا نشد</div>';
}
$('chats').addEventListener('click',e=>{
  const item=e.target.closest('.chat-item');
  if(!item)return;
  e.preventDefault();
  openConv(Number(item.dataset.id));
});
async function openConv(id){
  const found=convs.find(c=>Number(c.id)===Number(id));
  if(!found)return;
  current=found;
  const other=current.type==='direct'?current.members.find(x=>Number(x.id)!==Number(me.id)):null;
  if(socket?.connected)socket.emit('join',current.id);

  const av=$('chatAvatar');
  if(current.type==='direct' && other){
    av.innerHTML=other.avatar?`<img src="${esc(other.avatar)}" alt="">`:esc((other.display_name||'گ')[0]);
  }else{
    av.innerHTML=current.type==='channel'?'📢':current.type==='group'?'👥':'گ';
  }
  $('chatTitle').textContent=current.type==='direct'?(other?.display_name||'گفتگو'):current.name;
  $('chatTitle').onclick=current.type==='direct'&&other?()=>openUserProfile(other.id):null;
  $('chatTitle').style.cursor=current.type==='direct'&&other?'pointer':'default';
  $('chatStatus').textContent=current.type==='channel'?'📢 کانال':current.type==='group'?`👥 ${current.members.length} عضو`:(other?'@'+other.username:'گفتگوی خصوصی');
  const readOnly=current.type==='channel'&&Number(current.owner_id)!==Number(me.id);
  $('text').disabled=readOnly;
  $('send').disabled=readOnly;
  $('text').placeholder=readOnly?'فقط مدیر کانال می‌تواند پیام بفرستد':'پیامی بنویس...';
  $('messages').innerHTML='<div class="empty">در حال بارگذاری پیام‌ها…</div>';
  try{
    const ms=await api(`/api/conversations/${current.id}/messages`);
    $('messages').innerHTML='';
    ms.forEach(m=>{messageCache[m.id]=m;renderMessage(m)});
    if(!ms.length)$('messages').innerHTML='<div class="empty"><b>شروع گفتگو</b><span>اولین پیام را بفرست 👋</span></div>';
    if(!readOnly){$('text').removeAttribute('disabled');setTimeout(()=>$('text').focus(),0);}
    renderFilteredConvs();
  }catch(e){
    $('messages').innerHTML=`<div class="empty"><b>خطا در باز کردن گفتگو</b><span>${esc(e.message||'خطای ناشناخته')}</span></div>`;
  }
}
function fmtTime(s){return new Date(s).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}function fmtSec(sec){if(!isFinite(sec))return '00:00';sec=Math.max(0,Math.floor(sec));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function customAudio(url,name,voice=false){return `<div class="media-card custom-audio"><div class="audio-art"><div class="vinyl"></div></div><audio preload="metadata" src="${esc(url)}"></audio><div class="media-controls"><button class="play-btn">▶</button><input class="progress" type="range" min="0" max="100" value="0"><span class="time">00:00 / 00:00</span><input class="volume" type="range" min="0" max="1" step="0.05" value="1"><button class="speed-btn">1×</button></div><div style="padding:0 10px 9px;font-size:10px;color:#9eabc0">${voice?'🎙️ پیام صوتی':'🎵 '+esc(name||'آهنگ')}</div></div>`}
function customVideo(url){return `<div class="media-card custom-video"><div class="media-visual"><video class="video-el" preload="metadata" src="${esc(url)}"></video></div><div class="media-controls"><button class="play-btn">▶</button><input class="progress" type="range" min="0" max="100" value="0"><span class="time">00:00 / 00:00</span><input class="volume" type="range" min="0" max="1" step="0.05" value="1"><button class="speed-btn">1×</button><button class="full-btn">⛶</button></div></div>`}
function bindPlayers(root=document){root.querySelectorAll('.custom-audio,.custom-video').forEach(card=>{if(card.dataset.bound)return;card.dataset.bound='1';const media=card.querySelector('audio,video'),play=card.querySelector('.play-btn'),progress=card.querySelector('.progress'),time=card.querySelector('.time'),volume=card.querySelector('.volume'),speed=card.querySelector('.speed-btn'),full=card.querySelector('.full-btn');play.onclick=()=>media.paused?media.play():media.pause();media.onplay=()=>play.textContent='❚❚';media.onpause=()=>play.textContent='▶';media.ontimeupdate=()=>{progress.value=media.duration?(media.currentTime/media.duration*100):0;time.textContent=fmtSec(media.currentTime)+' / '+fmtSec(media.duration)};media.onloadedmetadata=()=>time.textContent='00:00 / '+fmtSec(media.duration);progress.oninput=()=>{if(media.duration)media.currentTime=media.duration*(progress.value/100)};volume.oninput=()=>media.volume=volume.value;let speeds=[1,1.25,1.5,2,.75];speed.onclick=()=>{let i=speeds.indexOf(media.playbackRate);media.playbackRate=speeds[(i+1)%speeds.length];speed.textContent=media.playbackRate+'×'};if(full)full.onclick=()=>media.requestFullscreen?.()})}
function renderMessage(m){if(!current||m.conversation_id!==current.id)return;const old=document.querySelector(`[data-msg="${m.id}"]`);if(old)return;const el=document.createElement('div');el.className='bubble '+(m.sender_id===me.id?'mine':'');el.dataset.msg=m.id;messageCache[m.id]=m;let body='';if(m.reply_to){const r=messageCache[m.reply_to];body+=`<div class="reply-ref">↩ ${esc(r?.text||'پیام چندرسانه‌ای')}</div>`}if(m.kind==='voice')body+=customAudio(m.file_url,'',true);else if(m.file_url&&m.file_type?.startsWith('image/'))body+=`<div class="media-card"><div class="media-visual"><img class="image-open" src="${esc(m.file_url)}" alt="تصویر"></div></div>${m.text?`<div>${esc(m.text)}</div>`:''}`;else if(m.file_url&&m.file_type?.startsWith('video/'))body+=customVideo(m.file_url);else if(m.file_url&&m.file_type?.startsWith('audio/'))body+=customAudio(m.file_url,m.file_name,false);else if(m.file_url)body+=`<div class="file-card"><span class="file-icon">📎</span><div class="file-name">${esc(m.file_name||'فایل')}</div><a href="${esc(m.file_url)}" target="_blank" rel="noopener" style="margin-right:auto;color:#a99aff">باز کردن</a></div>`;else body+=esc(m.text);el.innerHTML=`<div class="meta"><button class="sender-name" type="button">${esc(m.display_name||'کاربر')}</button><span>${fmtTime(m.created_at)}</span></div>${body}<div class="message-actions"><button class="reply-btn">↩ ریپلای</button><button class="react-btn">☺ واکنش</button>${m.sender_id===me.id?`<button class="delete-btn">حذف</button>`:''}<button class="save-btn">🔖 ذخیره</button></div><div class="reactions"></div>`;$('messages').appendChild(el);el.querySelector('.sender-name').onclick=()=>m.sender_id===me.id?openMyProfile():openUserProfile(m.sender_id);el.querySelector('.reply-btn').onclick=()=>startReply(m.id);el.querySelector('.react-btn').onclick=()=>showReact(m.id);el.querySelector('.delete-btn')?.addEventListener('click',()=>deleteMsg(m.id));el.querySelector('.save-btn')?.addEventListener('click',()=>saveMessage(m.id));el.querySelector('.image-open')?.addEventListener('click',()=>openImage(m.file_url));updateReactions(el,m.reactions||{});bindPlayers(el);$('messages').scrollTop=$('messages').scrollHeight}
function updateReactions(el,reactions){const box=el.querySelector('.reactions');if(!box)return;box.innerHTML=Object.entries(reactions||{}).filter(([,a])=>a.length).map(([e,a])=>`<button class="reaction ${a.includes(me.id)?'mine-react':''}" data-react="${esc(e)}">${e} ${a.length}</button>`).join('');box.querySelectorAll('[data-react]').forEach(b=>b.onclick=()=>react(Number(el.dataset.msg),b.dataset.react))}
function showReact(id){const el=document.querySelector(`[data-msg="${id}"]`);if(!el)return;el.querySelector('.quick-react')?.remove();const menu=document.createElement('div');menu.className='reactions quick-react';menu.innerHTML=['❤️','👍','😂','😮','😢','🔥','🎉','👏','😍','🤩','💯'].map(e=>`<button class="reaction" data-e="${e}">${e}</button>`).join('');el.appendChild(menu);menu.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{react(id,b.dataset.e);menu.remove()})}
function react(id,e){socket.emit('react',{messageId:id,emoji:e})}function startReply(id){replyTo=id;const r=messageCache[id];$('replyPreview').textContent=(r?.text|| (r?.kind==='voice'?'🎙️ پیام صوتی':r?.kind==='video'?'🎬 ویدیو':r?.kind==='audio'?'🎵 آهنگ':r?.kind==='image'?'🖼️ تصویر':'پیام')).slice(0,120);$('replyBar').classList.remove('hidden');$('text').focus()}function deleteMsg(id){if(confirm('این پیام حذف شود؟'))socket.emit('delete_message',id)}
$('composer').onsubmit=async e=>{e.preventDefault();if(!current||$('text').disabled)return;const text=$('text').value.trim();if(!text)return;const payload={conversationId:current.id,text,kind:'text',replyTo};$('text').value='';replyTo=null;$('replyBar').classList.add('hidden');try{await api('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(socket?.connected)socket.emit('typing',{conversationId:current.id,typing:false})}catch(err){$('text').value=text;alert(err.message||'ارسال پیام ناموفق بود')}};
$('text').oninput=()=>{if(!current||$('text').disabled)return;if(socket?.connected){socket.emit('typing',{conversationId:current.id,typing:true});clearTimeout(typingTimer);typingTimer=setTimeout(()=>socket.emit('typing',{conversationId:current.id,typing:false}),700)}};
$('attach').onclick=()=>$('file').click();$('file').onchange=async()=>{const f=$('file').files[0];if(!f||!current)return;try{const fd=new FormData();fd.append('file',f);const r=await api('/api/upload',{method:'POST',body:fd});let kind=r.mime.startsWith('image/')?'image':r.mime.startsWith('video/')?'video':r.mime.startsWith('audio/')?'audio':'file';socket.emit('send_message',{conversationId:current.id,fileUrl:r.url,fileName:r.name,fileType:r.mime,kind,replyTo})}catch(e){alert(e.message)}$('file').value='';replyTo=null;$('replyBar').classList.add('hidden')};
$('voice').onclick=async()=>{if(recording){recording.stop();return}if(!navigator.mediaDevices?.getUserMedia)return alert('مرورگر شما ضبط صدا را پشتیبانی نمی‌کند');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recording=new MediaRecorder(stream);recording.ondataavailable=e=>e.data.size&&recordChunks.push(e.data);recording.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(recordChunks,{type:recording?.mimeType||'audio/webm'});const fd=new FormData();fd.append('file',blob,'voice-'+Date.now()+'.webm');try{const r=await api('/api/upload',{method:'POST',body:fd});socket.emit('send_message',{conversationId:current.id,fileUrl:r.url,fileName:r.name,fileType:'audio/webm',kind:'voice',replyTo})}catch(e){alert(e.message)}recording=null;$('voice').textContent='🎙';$('voice').classList.remove('recording')};recording.start();$('voice').textContent='■';$('voice').classList.add('recording')}catch{alert('دسترسی میکروفون داده نشد')}};
$('emoji').onclick=()=>$('emojiPanel').classList.toggle('hidden');$('emojiClose').onclick=()=>$('emojiPanel').classList.add('hidden');$('emojiGrid').innerHTML=emojis.map(e=>`<button type="button">${e}</button>`).join('');document.querySelectorAll('#emojiGrid button').forEach(b=>b.onclick=()=>{$('text').value+=b.textContent;$('text').focus()});$('theme').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('gish_theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('gish_theme')==='light')document.body.classList.add('light');$('clearSearch').onclick=()=>{$('search').focus()};$('cancelReply').onclick=()=>{replyTo=null;$('replyBar').classList.add('hidden')};
async function searchUsers(){const q=$('search').value.trim();if(!q){$('userResults').innerHTML='';return}const us=await api('/api/users?q='+encodeURIComponent(q));$('userResults').innerHTML=us.map(u=>`<button class="chat-item" data-u="${u.id}">${avatarHTML(u)}<div class="ci"><b>${esc(u.display_name)}</b><small>@${esc(u.username)}</small></div></button>`).join('');document.querySelectorAll('[data-u]').forEach(b=>b.onclick=async()=>{const c=await api('/api/conversations/direct',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:Number(b.dataset.u)})});await loadConvs();openConv(c.id);$('search').value='';$('userResults').innerHTML=''})}$('search').oninput=searchUsers;
function modal(title,body,cb){$('modalTitle').textContent=title;$('modalBody').innerHTML=body;$('modal').classList.remove('hidden');$('modalOk').onclick=async()=>{try{await cb();$('modal').classList.add('hidden');await loadConvs()}catch(e){alert(e.message)}};$('modalCancel').onclick=()=>$('modal').classList.add('hidden');$('modalX').onclick=()=>$('modal').classList.add('hidden')}
$('newGroup').onclick=async()=>{const us=await api('/api/users');modal('ساخت گروه',`<input id="gName" placeholder="نام گروه"><input id="gDesc" placeholder="توضیح کوتاه"><div class="member-list">${us.map(u=>`<label class="member-row"><input type="checkbox" value="${u.id}">${esc(u.display_name)} (@${esc(u.username)})</label>`).join('')}</div>`,async()=>{const members=[...document.querySelectorAll('.member-list input:checked')].map(x=>Number(x.value));const c=await api('/api/conversations/group',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('gName').value,description:$('gDesc').value,members})});openConv(c.id)})};$('newChannel').onclick=()=>modal('ساخت کانال',`<input id="cName" placeholder="نام کانال"><input id="cUser" placeholder="شناسه انگلیسی، مثل gishnews"><input id="cDesc" placeholder="توضیح کانال">`,async()=>{const c=await api('/api/conversations/channel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('cName').value,username:$('cUser').value,description:$('cDesc').value})});openConv(c.id)});
async function changeAvatar(){const input=document.createElement('input');input.type='file';input.accept='image/*';input.onchange=async()=>{const f=input.files[0];if(!f)return;try{const fd=new FormData();fd.append('avatar',f);me=await api('/api/profile/avatar',{method:'POST',body:fd});refreshDrawerProfile();setMyAvatar(me)}catch(e){alert(e.message)}};input.click()}$('avatarBtn').onclick=changeAvatar;$('profileAvatarBtn').onclick=changeAvatar;$('editProfile').onclick=()=>{$('profileName').value=me.display_name;$('profileBio').value=me.bio||'';$('profileUser').textContent='@'+me.username;$('profileModal').classList.remove('hidden')};$('closeProfile').onclick=()=>$('profileModal').classList.add('hidden');$('saveProfile').onclick=async()=>{me=await api('/api/profile',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:$('profileName').value,bio:$('profileBio').value})});refreshDrawerProfile();setMyAvatar(me);$('profileModal').classList.add('hidden')};$('logout').onclick=()=>{localStorage.removeItem('gish_token');location.reload()};
$('lightboxClose').onclick=()=>$('lightbox').classList.add('hidden');$('lightbox').onclick=e=>{if(e.target===$('lightbox'))$('lightbox').classList.add('hidden')};function openImage(url){$('lightboxImg').src=url;$('lightbox').classList.remove('hidden')}
$('chatMore').onclick=()=>{if(current)alert(current.type==='channel'?'کانال گیش چت':current.type==='group'?'گروه گیش چت':'گفتگوی خصوصی')};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('loginForm').classList.toggle('hidden',b.dataset.tab!=='login');$('registerForm').classList.toggle('hidden',b.dataset.tab!=='register')});$('loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('loginEmail').value,password:$('loginPass').value})}).then(x=>x.json());if(r.error)throw Error(r.error);localStorage.setItem('gish_token',r.token);token=r.token;boot()}catch(e){$('authError').textContent=e.message}};$('registerForm').onsubmit=async e=>{e.preventDefault();try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({displayName:$('regName').value,email:$('regEmail').value,password:$('regPass').value})}).then(x=>x.json());if(r.error)throw Error(r.error);localStorage.setItem('gish_token',r.token);token=r.token;boot()}catch(e){$('authError').textContent=e.message}};
async function openUserProfile(id){try{const u=await api('/api/users/'+id+'/profile');$('viewProfileAvatar').innerHTML=u.avatar?`<img src="${esc(u.avatar)}" alt="">`:esc((u.display_name||'گ')[0]);$('viewProfileName').textContent=u.display_name||'کاربر';$('viewProfileUsername').textContent='@'+(u.username||'user');$('viewProfileId').textContent='@'+(u.username||'user');$('viewProfileBio').textContent=u.bio||'بیویی ثبت نشده است.';$('blockUserBtn').textContent=u.blocked?'♻️ رفع بلاک':'🚫 بلاک';$('blockUserBtn').dataset.id=id;$('reportUserBtn').dataset.id=id;$('profileActionStatus').textContent=u.blockedBy?'این کاربر شما را بلاک کرده است.':'';$('userProfileModal').classList.remove('hidden')}catch(e){alert(e.message)}}
function openMyProfile(){if(!me)return;openUserProfile(me.id).catch(()=>{})}
$('closeUserProfile').onclick=()=>$('userProfileModal').classList.add('hidden');
$('blockUserBtn').onclick=async()=>{const id=Number($('blockUserBtn').dataset.id);if(!id)return;try{const r=await api('/api/users/'+id+'/block',{method:'POST'});$('blockUserBtn').textContent=r.blocked?'♻️ رفع بلاک':'🚫 بلاک';$('profileActionStatus').textContent=r.blocked?'کاربر بلاک شد؛ پیام‌های دوطرفه ارسال نمی‌شوند.':'بلاک کاربر برداشته شد.'}catch(e){alert(e.message)}};
$('reportUserBtn').onclick=async()=>{const id=Number($('reportUserBtn').dataset.id);if(!id)return;const reason=prompt('دلیل گزارش را کوتاه بنویس:','رفتار نامناسب');if(reason===null)return;try{await api('/api/users/'+id+'/report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason})});$('profileActionStatus').textContent='گزارش شما ثبت شد.'}catch(e){alert(e.message)}};
$('userProfileModal').addEventListener('click',e=>{if(e.target.id==='userProfileModal')$('userProfileModal').classList.add('hidden')});

boot();

// v7 Telegram-style navigation, drawer and settings
function syncThemeUI(){const dark=document.body.classList.contains('dark');$('themeState').textContent=dark?'روشن':'خاموش';$('settingsTheme').classList.toggle('on',dark);$('theme').textContent=dark?'☀':'☾'}
function applyV7Theme(dark){document.body.classList.toggle('dark',dark);localStorage.setItem('gish_theme',dark?'dark':'light');syncThemeUI()}
function openDrawer(){$('drawer').classList.add('open');$('drawerShade').classList.remove('hidden')}
function closeDrawer(){$('drawer').classList.remove('open');$('drawerShade').classList.add('hidden')}
function refreshDrawerProfile(){if(!me)return;$('drawerName').textContent=me.display_name;$('drawerUser').textContent='@'+me.username;const box=$('drawerAvatar');box.innerHTML=me.avatar?`<img src="${esc(me.avatar)}" alt="">`:`<span>${esc((me.display_name||'گ')[0])}</span>`;const s=$('settingsAvatar');s.innerHTML=me.avatar?`<img src="${esc(me.avatar)}" alt="">`:esc((me.display_name||'گ')[0]);$('settingsName').textContent=me.display_name;$('settingsUsername').textContent='@'+me.username}
setTimeout(()=>{if(me)refreshDrawerProfile();syncThemeUI()},700);
$('menuBtn').onclick=openDrawer;$('mobileMenu').onclick=openDrawer;$('drawerShade').onclick=closeDrawer;
$('drawerTheme').onclick=()=>applyV7Theme(!document.body.classList.contains('dark'));
$('theme').onclick=()=>applyV7Theme(!document.body.classList.contains('dark'));
$('drawerSettings').onclick=()=>{$('settingsModal').classList.remove('hidden');closeDrawer();refreshDrawerProfile()};$('closeSettings').onclick=()=>$('settingsModal').classList.add('hidden');$('settingsTheme').onclick=()=>applyV7Theme(!document.body.classList.contains('dark'));
$('compactSwitch').onclick=()=>{const on=!document.body.classList.contains('compact');document.body.classList.toggle('compact',on);$('compactSwitch').classList.toggle('on',on);localStorage.setItem('gish_compact',on?'1':'0')};
$('motionSwitch').onclick=()=>{const on=document.body.classList.contains('no-motion');document.body.classList.toggle('no-motion',!on);$('motionSwitch').classList.toggle('on',on);localStorage.setItem('gish_motion',on?'1':'0')};
$('drawerProfile').onclick=()=>{$('editProfile').click();closeDrawer()};$('drawerAvatar').onclick=()=>{$('avatarBtn').click();closeDrawer()};$('drawerNewGroup').onclick=()=>{$('newGroup')?.click();closeDrawer()};$('drawerNewChannel').onclick=()=>{$('newChannel')?.click();closeDrawer()};$('drawerLogout').onclick=()=>{$('logout').click()};$('drawerSaved').onclick=()=>openSaved();$('chatSearch').onclick=()=>{$('search').focus();openDrawer()};
if(localStorage.getItem('gish_theme')==='dark')document.body.classList.add('dark');if(localStorage.getItem('gish_compact')==='1'){document.body.classList.add('compact');$('compactSwitch').classList.add('on')}if(localStorage.getItem('gish_motion')==='1'){document.body.classList.add('no-motion');$('motionSwitch').classList.remove('on')}
// Conversation filter tabs
let activeFilter='all';document.querySelectorAll('.chat-tabs button').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('.chat-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=['all','direct','group','channel'][i];renderFilteredConvs()});

// v10: Saved Messages + WebRTC calling
async function saveMessage(id){try{const r=await api('/api/saved/'+id,{method:'POST'});const b=document.querySelector(`[data-msg="${id}"] .save-btn`);if(b)b.textContent=r.saved?'🔖 ذخیره شد':'🔖 ذخیره';}catch(e){alert(e.message)}}
async function openSaved(){closeDrawer();$('savedModal').classList.remove('hidden');$('savedList').innerHTML='<div class="empty">در حال بارگذاری…</div>';try{const items=await api('/api/saved');if(!items.length){$('savedList').innerHTML='<div class="empty">هنوز پیامی ذخیره نکرده‌ای.</div>';return}$('savedList').innerHTML=items.map(x=>{const m=x.message;let content=m.text||({voice:'🎙️ پیام صوتی',video:'🎬 ویدیو',audio:'🎵 آهنگ',image:'🖼️ تصویر'}[m.kind]||'📎 فایل');return `<button class="saved-item" data-open="${m.conversation_id}"><div class="saved-icon">🔖</div><div><b>${esc(m.display_name||'کاربر')}</b><small>${esc(content).slice(0,120)}</small><time>${fmtTime(m.created_at)}</time></div></button>`}).join('');document.querySelectorAll('.saved-item').forEach(b=>b.onclick=()=>{$('savedModal').classList.add('hidden');openConv(Number(b.dataset.open))})}catch(e){$('savedList').innerHTML='<div class="empty">خطا در دریافت پیام‌ها</div>'}}
$('closeSaved').onclick=()=>$('savedModal').classList.add('hidden');

let pc=null,localStream=null,callPeer=null,callVideo=false,callMuted=false,callCamera=true;
function callOther(){if(!current||current.type!=='direct'){alert('تماس فقط در گفتگوی خصوصی فعال است.');return current?.type==='direct'}return current.members.find(u=>u.id!==me.id)}
async function beginCall(video){const peer=callOther();if(!peer)return;callPeer=peer.id;callVideo=video;$('callType').textContent=video?'تماس تصویری':'تماس صوتی';$('callName').textContent=peer.display_name;const av=$('callAvatar');av.innerHTML=peer.avatar?`<img src="${esc(peer.avatar)}" alt="">`:esc((peer.display_name||'گ')[0]);$('callModal').classList.remove('hidden');$('acceptCall').classList.add('hidden');$('rejectCall').classList.add('hidden');try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:video});$('localVideo').srcObject=video?localStream:null;$('localVideo').classList.toggle('hidden',!video);pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));pc.onicecandidate=e=>e.candidate&&socket.emit('call:ice',{to:callPeer,candidate:e.candidate});pc.ontrack=e=>{$('remoteVideo').srcObject=e.streams[0];$('remoteVideo').classList.toggle('hidden',!callVideo);$('callAvatar').classList.toggle('hidden',true)};const offer=await pc.createOffer();await pc.setLocalDescription(offer);socket.emit('call:offer',{to:callPeer,offer,video});}catch(e){endCall(true);alert('دسترسی میکروفون/دوربین ممکن نیست.')} }
async function acceptCall(){if(!pc||!localStream)return;}
function cleanupCall(){try{localStream?.getTracks().forEach(t=>t.stop());pc?.close()}catch{}localStream=null;pc=null;callPeer=null;$('localVideo').srcObject=null;$('remoteVideo').srcObject=null;$('callModal').classList.add('hidden');$('callAvatar').classList.remove('hidden')}
function endCall(silent=false){if(callPeer&&!silent)socket?.emit('call:end',{to:callPeer});cleanupCall()}
$('callAudio').onclick=()=>beginCall(false);$('callVideo').onclick=()=>beginCall(true);$('endCall').onclick=()=>endCall();$('muteCall').onclick=()=>{callMuted=!callMuted;localStream?.getAudioTracks().forEach(t=>t.enabled=!callMuted);$('muteCall').textContent=callMuted?'🔇':'🎙'};$('cameraCall').onclick=()=>{callCamera=!callCamera;localStream?.getVideoTracks().forEach(t=>t.enabled=callCamera);$('cameraCall').textContent=callCamera?'▣':'🚫'};
function installCallHandlers(){if(!socket)return;socket.on('call:offer',async d=>{if(pc)return;callPeer=Number(d.from);callVideo=!!d.video;const u=await api('/api/users').then(xs=>xs.find(x=>x.id===callPeer)).catch(()=>null);$('callType').textContent=callVideo?'تماس تصویری ورودی':'تماس صوتی ورودی';$('callName').textContent=u?.display_name||'کاربر';$('callModal').classList.remove('hidden');$('acceptCall').classList.remove('hidden');$('rejectCall').classList.remove('hidden');$('endCall').onclick=()=>{socket.emit('call:end',{to:callPeer});cleanupCall()};window.pendingOffer=d.offer;window.pendingCaller=d.from;});socket.on('call:answer',async d=>{if(pc&&d.from===callPeer)await pc.setRemoteDescription(new RTCSessionDescription(d.answer))});socket.on('call:ice',async d=>{if(pc&&d.from===callPeer){try{await pc.addIceCandidate(d.candidate)}catch{}}});socket.on('call:end',d=>{if(d.from===callPeer)cleanupCall()});}
$('acceptCall').onclick=async()=>{const peer=callPeer;try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:callVideo});$('localVideo').srcObject=callVideo?localStream:null;$('localVideo').classList.toggle('hidden',!callVideo);pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});localStream.getTracks().forEach(t=>pc.addTrack(t));pc.onicecandidate=e=>e.candidate&&socket.emit('call:ice',{to:peer,candidate:e.candidate});pc.ontrack=e=>{$('remoteVideo').srcObject=e.streams[0];$('remoteVideo').classList.toggle('hidden',!callVideo);$('callAvatar').classList.add('hidden')};await pc.setRemoteDescription(new RTCSessionDescription(window.pendingOffer));const answer=await pc.createAnswer();await pc.setLocalDescription(answer);socket.emit('call:answer',{to:peer,answer});$('acceptCall').classList.add('hidden');$('rejectCall').classList.add('hidden');}catch{endCall(true);alert('دسترسی میکروفون/دوربین داده نشد')}};$('rejectCall').onclick=()=>endCall();

